class Relation:

    START_ID = ':START_ID'
    END_ID = ':END_ID'
    TYPE = ':TYPE'
    ALL = [START_ID, END_ID, TYPE]


class NodeField:

    ID = 'nodeId:ID'
    LABEL = ':LABEL'
    FULLTIME_HOME_GOALS = 'fulltimeHomeGoals'
    FULLTIME_AWAY_GOALS = 'fulltimeAwayGoals'
    HOME_ODDS = 'homeOdds'
    AWAY_ODDS = 'awayOdds'
    DRAW_ODDS = 'drawOdds'
    OVER_25_GOAL_ODDS = 'over25GoalOdds'
    UNDER_25_GOAL_ODDS = 'under25GoalOdds'
    BOTH_TEAMS_TO_SCORE_ODDS = 'bothTeamsToScoreOdds'
    NOT_BOTH_TEAMS_TO_SCORE_ODDS = 'notBothTeamsToScoreOdds'
    MATCH_EVENT_TIME = 'matchEventTime'
    SHOT_PLACEMENT = 'shotPlacement'
    SHOT_OUTCOME = 'shotOutcome'
    WAS_GOAL = 'wasGoal'
    PITCH_LOCATION = 'pitchLocation'
    BODYPART = 'bodypart'
    ASSIST_METHOD = 'assistMethod'
    SITUATION = 'situation'
    WAS_FAST_BREAK = 'wasFastBreak'
    TEXT = 'text'
    ALL = [
        ID, LABEL, FULLTIME_HOME_GOALS, FULLTIME_AWAY_GOALS, HOME_ODDS, AWAY_ODDS, DRAW_ODDS, OVER_25_GOAL_ODDS,
        UNDER_25_GOAL_ODDS, BOTH_TEAMS_TO_SCORE_ODDS, NOT_BOTH_TEAMS_TO_SCORE_ODDS, MATCH_EVENT_TIME, SHOT_PLACEMENT,
        SHOT_OUTCOME, WAS_GOAL, PITCH_LOCATION, BODYPART, ASSIST_METHOD, SITUATION, WAS_FAST_BREAK, TEXT
    ]


class NodeLabel:

    ANNOUNCEMENT = 'ANNOUNCEMENT'
    CORNER = 'CORNER'
    COUNTRY = 'COUNTRY'
    DATE = 'DATE'
    ENTITY = 'ENTITY'
    FAILED_THROUGH_BALL = 'FAILED_THROUGH_BALL'
    FREE_KICK_WON = 'FREE_KICK_WON'
    FOUL = 'FOUL'
    HANDBALL = 'HANDBALL'
    KEY_PASS = 'KEY_PASS'
    LEAGUE = 'LEAGUE'
    MATCH = 'MATCH'
    MATCH_EVENT = 'MATCH_EVENT'
    MONTH = 'MONTH'
    OFFSIDE = 'OFFSIDE'
    OWN_GOAL = 'OWN_GOAL'
    PENALTY_CONCEDED = 'PENALTY_CONCEDED'
    PLAYER = 'PLAYER'
    RED_CARD = 'RED_CARD'
    SEASON = 'SEASON'
    SECOND_YELLOW_CARD = 'SECOND_YELLOW_CARD'
    SENDING_OFF = 'SENDING_OFF'
    SHOT_ATTEMPT = 'SHOT_ATTEMPT'
    SUBSTITUTION = 'SUBSTITUTION'
    TEAM = 'TEAM'
    YEAR = 'YEAR'
    YELLOW_CARD = 'YELLOW_CARD'


class RelationType:

    AWAY_TEAM = 'AWAY_TEAM'
    HOME_TEAM = 'HOME_TEAM'
    IN_COUNTRY = 'IN_COUNTRY'
    IN_LEAGUE = 'IN_LEAGUE'
    IN_MONTH = 'IN_MONTH'
    IN_SEASON = 'IN_SEASON'
    IN_YEAR = 'IN_YEAR'
    MATCH_EVENT = 'MATCH_EVENT'
    NEXT = 'NEXT'
    ON_DATE = 'ON_DATE'
