class Relation:

    START_ID = ':START_ID'
    END_ID = ':END_ID'
    TYPE = ':TYPE'
    ALL = [START_ID, END_ID, TYPE]


class EventRelationType:

    EVENT_TEAM = 'EVENT_TEAM'
    OPPONENT_TEAM = 'OPPONENT_TEAM'
    PLAYER_1 = 'PLAYER_1'
    PLAYER_2 = 'PLAYER_2'
    SHOT_PLACEMENT = 'SHOT_PLACEMENT'
    SHOT_OUTCOME = 'SHOT_OUTCOME'
    IS_GOAL = 'IS_GOAL'
    PITCH_LOCATION = 'PITCH_LOCATION'
    BODY_PART = 'BODY_PART'
    ASSIST_METHOD = 'ASSIST_METHOD'
    EVENT_SITUATION = 'EVENT_SITUATION'
    FAST_BREAK = 'FAST_BREAK'


class GeneralRelationType:

    AWAY_TEAM = 'AWAY_TEAM'
    HOME_TEAM = 'HOME_TEAM'
    HAS_MATCH_EVENT = 'HAS_MATCH_EVENT'
    IN_COUNTRY = 'IN_COUNTRY'
    IN_LEAGUE = 'IN_LEAGUE'
    IN_MONTH = 'IN_MONTH'
    IN_SEASON = 'IN_SEASON'
    IN_YEAR = 'IN_YEAR'
    NEXT = 'NEXT'
    ON_DATE = 'ON_DATE'
